### PR TITLE
Fix Header and CTA responsiveness

### PR DESCRIPTION
**Pull request by iamsolankiamit**
Change-type: minor
Signed-off-by: Amit Solanki <amit@balena.io>

### CODE REVIEW

**Comment by iamsolankiamit** [comment]
@balena-ci rebase

**Review by sradevski — APPROVED** [review]

**Comment by iamsolankiamit** [comment]
@balena-ci rebase

**Comment by iamsolankiamit** [comment]
@balena-ci rebase

**Comment by iamsolankiamit** [comment]
@balena-ci rebase

**Comment by sradevski** [comment]
@iamsolankiamit we dont care about NPM (I actually thought we are not publishing anymore), I'll merge it.

**Pull request merged**
