### PR TITLE
Adds fold4covid.com redirects and accessing any page redirects to `/`.

### PR DESCRIPTION
**Pull request by cmfcruz**
Change-type: patch
Signed-off-by: Carlo Miguel Cruz <carloc@balena.io>

### CODE REVIEW

**Review by sradevski — APPROVED** [review]

**Review by iamsolankiamit — APPROVED** [review]

**Comment by cmfcruz** [comment]
@balena-ci rebase

**Comment by sradevski** [comment]
@cmfcruz I saw versionist failed earlier,  I think it has to do something with your commit message, maybe remove any special characters?

**Comment by sradevski** [comment]
@balena-ci rebase

**Comment by cmfcruz** [comment]
I amended my commit message to remove '`' characters.

**Comment by cmfcruz** [comment]
@balena-ci rebase

**Pull request merged**
