### PR TITLE
Correct wording on map overlay

### PR DESCRIPTION
**Pull request by iamsolankiamit**
Connects-to: #48
Change-type: minor
Signed-off-by: Amit Solanki <amit@balena.io>

### CODE REVIEW

**Comment by sradevski** [comment]
@iamsolankiamit we were saying to be left-aligned, but within the center column in thecall (so the leftmost side of it should align with the numbering in `Getting started` section.

**Review by sradevski — APPROVED** [review]

**Comment by iamsolankiamit** [comment]
@balena-ci rebase

**Comment by iamsolankiamit** [comment]
@balena-ci rebase

**Comment by iamsolankiamit** [comment]
@balena-ci rebase

**Pull request merged**
