### PR TITLE
Updated FAQs with bonjour info

### LINKED ISSUE #116: Mention that avahi/bonjour is required for foldforcovid.local to work
Maybe like we do in the CLI docs:

On Windows, check if 'Bonjour' is installed (Control Panel > Programs and Features). If not, you can download Bonjour for Windows from https://support.apple.com/kb/DL999
Most 'desktop' Linux distributions ship with Avahi. Search for the installation command for your distribution. E.g. for Ubuntu: sudo apt-get install avahi-daemon
macOS comes with Bonjour built-in.

### PR DESCRIPTION
**Pull request by chrisys**
Fixes #116 

Change-type: patch
Signed-off-by: Chris Crocker-White <chriscw@balena.io>

### CODE REVIEW

**Review by iamsolankiamit — APPROVED** [review]

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by chrisys** [comment]
@balena-ci rebase

**Pull request merged**
